import { jsPDF } from "jspdf";
import type { Lang } from "@/lib/i18n";

export type PdfRow = { label: string; value: string };

export type FreightPdfPayload = {
  lang: Lang;
  pageTitle: string; // e.g. "Fret maritime (CBM)"
  subtitle?: string; // short description line
  params: PdfRow[]; // input recap (rate, dimensions, weight, etc.)
  results: PdfRow[]; // computed values (volume, total cost, etc.)
  transit?: string; // e.g. "45 à 60 jours"
  arrival?: string; // free text arrival sentence
  code?: string; // activation code (will be masked)
};

const BRAND = "Freight-Calculator";
const FOOTER = "By Mr.G  ·  +228 99584808  ·  fret-calculator.lovable.app";

function maskCode(code?: string): string | null {
  if (!code) return null;
  const c = code.trim();
  if (c.length <= 4) return c;
  return `****-${c.slice(-4)}`;
}

function formatNow(lang: Lang): string {
  return new Intl.DateTimeFormat(lang === "fr" ? "fr-FR" : "en-US", {
    day: "2-digit",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date());
}

function slugify(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

export function generateFreightPdf(payload: FreightPdfPayload): void {
  const isFr = payload.lang !== "en";
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48; // margin
  let y = M;

  // ---- Header bar ----
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, W, 90, "F");

  // Brand mark (small square)
  doc.setFillColor(59, 130, 246); // blue-500
  doc.roundedRect(M, 30, 30, 30, 6, 6, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(BRAND, M + 42, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(isFr ? "Récapitulatif de calcul" : "Calculation summary", M + 42, 68);

  // Date (right) — no code displayed (kept private)
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  const dateStr = formatNow(payload.lang);
  doc.text(dateStr, W - M, 60, { align: "right" });

  y = 140;

  // ---- Title (centered) ----
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(payload.pageTitle, W / 2, y, { align: "center" });
  y += 28;

  // ---- Section: Parameters ----
  y = drawSection(
    doc,
    isFr ? "Paramètres" : "Parameters",
    payload.params,
    M,
    y,
    W - 2 * M,
  );

  y += 22;

  // ---- Section: Results ----
  y = drawSection(
    doc,
    isFr ? "Résultats" : "Results",
    payload.results,
    M,
    y,
    W - 2 * M,
    true,
  );

  // ---- Transit / Arrival (highlighted hero block) ----
  if (payload.transit || payload.arrival) {
    y += 24;
    const boxX = M;
    const boxW = W - 2 * M;
    const boxH = 96;

    // Gradient-like layered fills (blue accent)
    doc.setFillColor(37, 99, 235); // blue-600
    doc.roundedRect(boxX, y, boxW, boxH, 12, 12, "F");

    // Soft inner overlay for depth
    doc.setFillColor(59, 130, 246); // blue-500
    doc.roundedRect(boxX + 4, y + 4, boxW - 8, boxH - 8, 10, 10, "F");

    // Left accent bar
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(boxX + 16, y + 18, 4, boxH - 36, 2, 2, "F");

    let ty = y + 32;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(219, 234, 254); // blue-100
    doc.text(
      (isFr ? "Délai estimé" : "Estimated transit").toUpperCase(),
      boxX + 32,
      ty,
    );
    ty += 20;

    if (payload.transit) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      doc.setTextColor(255, 255, 255);
      doc.text(payload.transit, boxX + 32, ty);
      ty += 18;
    }
    if (payload.arrival) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(226, 232, 240); // slate-200
      const lines = doc.splitTextToSize(payload.arrival, boxW - 64);
      doc.text(lines, boxX + 32, ty);
    }

    y += boxH + 8;
  }

  // ---- Footer ----
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(M, H - 50, W - M, H - 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(FOOTER, M, H - 32);
  doc.text(
    isFr
      ? "Document généré par Freight-Calculator. Tarifs et délais indicatifs."
      : "Document generated by Freight-Calculator. Rates and timing are indicative.",
    M,
    H - 20,
  );

  const filename = `freight-${slugify(payload.pageTitle)}-${Date.now()}.pdf`;
  doc.save(filename);
}

function drawSection(
  doc: jsPDF,
  title: string,
  rows: PdfRow[],
  x: number,
  y: number,
  width: number,
  emphasize = false,
): number {
  // Section title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text(title.toUpperCase(), x, y);
  y += 10;

  // Card
  const rowH = 26;
  const padding = 12;
  const cardH = padding * 2 + rows.length * rowH;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.8);
  doc.roundedRect(x, y, width, cardH, 8, 8, "FD");

  let ry = y + padding + 16;
  rows.forEach((row, i) => {
    if (i > 0) {
      doc.setDrawColor(241, 245, 249);
      doc.line(x + 12, ry - 18, x + width - 12, ry - 18);
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(row.label, x + 14, ry);

    doc.setFont("helvetica", emphasize ? "bold" : "normal");
    doc.setFontSize(emphasize ? 12 : 11);
    doc.setTextColor(15, 23, 42);
    doc.text(row.value, x + width - 14, ry, { align: "right" });

    ry += rowH;
  });

  return y + cardH;
}
