/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentCancelRouteImport } from './routes/payment-cancel'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivatedRouteImport } from './routes/activated'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSeaRouteImport } from './routes/app.sea'
import { Route as AppMultiRouteImport } from './routes/app.multi'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppAirRouteImport } from './routes/app.air'
import { Route as ApiPublicMoneyfusionWebhookRouteImport } from './routes/api.public.moneyfusion-webhook'

const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment-cancel',
  path: '/payment-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivatedRoute = ActivatedRouteImport.update({
  id: '/activated',
  path: '/activated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeaRoute = AppSeaRouteImport.update({
  id: '/sea',
  path: '/sea',
  getParentRoute: () => AppRoute,
} as any)
const AppMultiRoute = AppMultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppAirRoute = AppAirRouteImport.update({
  id: '/air',
  path: '/air',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMoneyfusionWebhookRoute =
  ApiPublicMoneyfusionWebhookRouteImport.update({
    id: '/api/public/moneyfusion-webhook',
    path: '/api/public/moneyfusion-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activated': typeof ActivatedRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/app/air': typeof AppAirRoute
  '/app/compare': typeof AppCompareRoute
  '/app/multi': typeof AppMultiRoute
  '/app/sea': typeof AppSeaRoute
  '/app/': typeof AppIndexRoute
  '/api/public/moneyfusion-webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activated': typeof ActivatedRoute
  '/admin': typeof AdminRoute
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/app/air': typeof AppAirRoute
  '/app/compare': typeof AppCompareRoute
  '/app/multi': typeof AppMultiRoute
  '/app/sea': typeof AppSeaRoute
  '/app': typeof AppIndexRoute
  '/api/public/moneyfusion-webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activated': typeof ActivatedRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/app/air': typeof AppAirRoute
  '/app/compare': typeof AppCompareRoute
  '/app/multi': typeof AppMultiRoute
  '/app/sea': typeof AppSeaRoute
  '/app/': typeof AppIndexRoute
  '/api/public/moneyfusion-webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activated'
    | '/admin'
    | '/app'
    | '/payment-cancel'
    | '/payment-success'
    | '/app/air'
    | '/app/compare'
    | '/app/multi'
    | '/app/sea'
    | '/app/'
    | '/api/public/moneyfusion-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activated'
    | '/admin'
    | '/payment-cancel'
    | '/payment-success'
    | '/app/air'
    | '/app/compare'
    | '/app/multi'
    | '/app/sea'
    | '/app'
    | '/api/public/moneyfusion-webhook'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/activated'
    | '/admin'
    | '/app'
    | '/payment-cancel'
    | '/payment-success'
    | '/app/air'
    | '/app/compare'
    | '/app/multi'
    | '/app/sea'
    | '/app/'
    | '/api/public/moneyfusion-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ActivatedRoute: typeof ActivatedRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicMoneyfusionWebhookRoute: typeof ApiPublicMoneyfusionWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-cancel': {
      id: '/payment-cancel'
      path: '/payment-cancel'
      fullPath: '/payment-cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activated': {
      id: '/activated'
      path: '/activated'
      fullPath: '/activated'
      preLoaderRoute: typeof ActivatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sea': {
      id: '/app/sea'
      path: '/sea'
      fullPath: '/app/sea'
      preLoaderRoute: typeof AppSeaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/multi': {
      id: '/app/multi'
      path: '/multi'
      fullPath: '/app/multi'
      preLoaderRoute: typeof AppMultiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/air': {
      id: '/app/air'
      path: '/air'
      fullPath: '/app/air'
      preLoaderRoute: typeof AppAirRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/moneyfusion-webhook': {
      id: '/api/public/moneyfusion-webhook'
      path: '/api/public/moneyfusion-webhook'
      fullPath: '/api/public/moneyfusion-webhook'
      preLoaderRoute: typeof ApiPublicMoneyfusionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAirRoute: typeof AppAirRoute
  AppCompareRoute: typeof AppCompareRoute
  AppMultiRoute: typeof AppMultiRoute
  AppSeaRoute: typeof AppSeaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAirRoute: AppAirRoute,
  AppCompareRoute: AppCompareRoute,
  AppMultiRoute: AppMultiRoute,
  AppSeaRoute: AppSeaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ActivatedRoute: ActivatedRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicMoneyfusionWebhookRoute: ApiPublicMoneyfusionWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
